apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::123264127435:user/devops-training-user
      username: devops-training-user
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::123264127435:role/prod-eks-node-group-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
