apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: coffeeshop
type: Opaque
data:
  connection-string: cG9zdGdyZXM6Ly9jb2ZmZWVzaG9wX3VzZXI6ZGV2X3Bhc3N3b3JkQHBvc3RncmVzOjU0MzIvY29mZmVlc2hvcA==  # postgres://coffeeshop_user:dev_password@postgres:5432/coffeeshop
  dsn-string: cG9zdGdyZXM6Ly9jb2ZmZWVzaG9wX3VzZXI6ZGV2X3Bhc3N3b3JkQHBvc3RncmVzOjU0MzIvY29mZmVlc2hvcA==  # postgres://coffeeshop_user:dev_password@postgres:5432/coffeeshop
